name: CD - Dev

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag to deploy (defaults to branch tag or latest)'
        required: false
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-build-push:
    name: Test, Build, Scan and Push (Dev)
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.version }}
      tags: ${{ steps.meta.outputs.tags }}
      primary_tag: ${{ steps.primary.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Read project version
        id: ver
        run: |
          VERSION=$(grep "^version\\s*=\\s*'.*'" build.gradle | sed -E "s/.*'([^']+)'.*/\\1/")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=short
            # add version-branch tag (e.g., 2025.0.0-develop)
            type=raw,value=${{ steps.ver.outputs.version }}-${{ github.ref_name }},enable=${{ startsWith(github.ref, 'refs/heads/') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (load to Docker for scanning)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Choose primary tag
        id: primary
        run: |
          first_tag=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
          echo "tag=$first_tag" >> $GITHUB_OUTPUT

      - name: Trivy image scan (High/Critical fail)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.primary.outputs.tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'

      - name: Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Dev EC2
    needs: test-build-push
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.test-build-push.outputs.version }}
    steps:
      - name: Use version
        run: echo "Resolved version is $VERSION"

      - name: Resolve image tag
        id: tag
        run: |
          if [ -n "${{ inputs.imageTag }}" ]; then
            # Respect explicitly provided tag as-is
            echo "tag=${{ inputs.imageTag }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/heads/* ]]; then
            # Compose version-branch (e.g., 2025.0.0-develop)
            echo "tag=${VERSION}-${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          else
            # Fallback to version-develop if not a branch ref
            echo "tag=${VERSION}-develop" >> $GITHUB_OUTPUT
          fi

      - name: Prepare image name
        id: image
        run: |
          echo "full=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy deploy script
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          port: 22
          source: "scripts/deploy.sh"
          target: "~/stake-api-service-dev"
          key: ${{ secrets.EC2_DEV_SSH_KEY }}

      - name: Copy deployment yaml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          port: 22
          source: "./docker-compose.prod.yml"
          target: "~/stake-api-service-dev"
          key: ${{ secrets.EC2_DEV_SSH_KEY }}

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          key: ${{ secrets.EC2_DEV_SSH_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            mkdir -p ~/stake-api-service-dev
            mkdir -p ~/app/logs
            cd ~/stake-api-service-dev
            chmod +x ./scripts/deploy.sh
            pwd
            echo "Logging into GHCR"
            echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            echo "Deploying to EC2 - Image Name " ${{ env.IMAGE_NAME }}
            export SPRING_PROFILE=dev
            export CONFIG_SERVER_HOST="${{ secrets.CONFIG_SERVER_HOST_DEV }}"
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_USERNAME="${{ secrets.DB_USERNAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export REDIS_HOST="${{ secrets.REDIS_HOST }}"
            export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
            export IMAGE_NAME="${{ steps.image.outputs.full }}"
            echo $IMAGE_NAME
            ./scripts/deploy.sh